language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# addons:
#   sonarcloud:
#     organization: "germanuclm"
#     token: ${SONAR_TOKEN}
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GermanUCLM_SIGET-Equipo3
  - mvn test